### ISSUE TITLE
Thread pools

### ISSUE THREAD

**Issue by carmas123** [mcxiaoke/kotlin-koi#1]
Please can you explain me how can I solve my problem:
I need to downloadload ListView items images into an async task and I think that creating a some like this can work:

```
asyncSafe {
  val image = downloadImage(myUrl)

  mainThreadSafe {
            assignImageToImageView(image)
  }
}
```

and call this into onBindViewHolder.

My problem is that this method can create hundreds threads and degrade the performance :(

I want to make a list of threads with an execution limit (like 5 for example) at a time.

Can be this with your fantastic utils?

**Comment by mcxiaoke** [comment]
@carmas123 

```
asyncSafe(executor) {
  val image = downloadImage(myUrl)

  mainThreadSafe {
            assignImageToImageView(image)
  }
}
```

**Comment by mcxiaoke** [comment]
readme is already updated.
